import "./globals.css"
import { DM_Sans } from "next/font/google"

const dm = DM_Sans({ weight: ["400", "500", "700"], subsets: ["latin"] })

export const metadata = {
    title: "Next JS Fullstack App",
    description: "Generated by loved from VArtz!",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={dm.className}>{children}</body>
        </html>
    )
}
